/* Le parcours : des leçons courtes, dans l'ordre, du tout premier Do aux deux mains.
 * Chaque leçon est un petit morceau à jouer (voir notes.js pour le format) + quelques explications. */
import { ODE_D, ODE_G, CLAIR_D, FRERE_D, JINGLE_D, ANNIV_D, DOUCE_D, DOUCE_G, CANON_D, CANON_G, HANON_D, HANON_G } from './airs.js';

export const NIVEAUX = [
  { n:1, nom:'Débutant — Les premiers pas' },
  { n:2, nom:'Débutant + — Deux mains' },
  { n:3, nom:'Intermédiaire — Dièses, bémols et accords' },
  { n:4, nom:'Confirmé — Accompagner' },
  { n:5, nom:'Avancé — Vitesse et précision' }
];

const DOIGTS = '<p class="muted small">Numéros des doigts : 1 = pouce, 2 = index, 3 = majeur, 4 = annulaire, 5 = auriculaire.</p>';
const HAUT = "<p><b>Comment jouer ici :</b> les notes à jouer s'allument en couleur, sur la partition et sur le clavier. L'appli t'écoute : dès que c'est juste, elle passe à la suite.</p>";

export const LECONS = [
  /* ---------------- niveau 1 ---------------- */
  { id:'l01', niveau:1, titre:'Trouver le Do', duree:'10 min', tempo:60, sig:'4/4',
    objectif:"Repérer le Do sur le clavier et jouer une note avec le pouce de la main droite.",
    contenu:`<p>Regarde les touches noires : elles sont groupées par <b>2</b> et par <b>3</b>. Le <b>Do</b> est la touche blanche juste à gauche d'un groupe de <b>2</b> touches noires.</p>
      <p>Le <b>Do central</b> (celui du milieu du piano, à peu près en face de toi) s'écrit sur la première ligne supplémentaire sous la portée en clé de sol.</p>${HAUT}${DOIGTS}`,
    conseils:["Assieds-toi au milieu du clavier, dos droit, poignets à la hauteur des touches.", "Joue avec le bout du pouce, doigt courbé."],
    d:'C4:1@1 C4@1 C4@1 C4@1 | C4:2@1 C4:2@1 | C4:4@1' },
  { id:'l02', niveau:1, titre:'Do, Ré, Mi', duree:'10 min', tempo:60, sig:'4/4',
    objectif:"Jouer trois notes qui se suivent avec trois doigts : pouce, index, majeur.",
    contenu:`<p>Pose le pouce (1) sur Do, l'index (2) sur Ré, le majeur (3) sur Mi. Chaque doigt a sa touche : <b>ne regarde pas tes mains</b>, regarde la partition.</p>
      <p>Sur la portée, quand la note monte, elle se déplace vers le haut.</p>${HAUT}${DOIGTS}`,
    conseils:["Garde la main souple : les doigts ne se lèvent que très peu."],
    d:'C4:1@1 D4@2 E4@3 D4@2 | C4@1 D4@2 E4@3 D4@2 | E4:2@3 D4:1@2 C4:1@1 | C4:4@1' },
  { id:'l03', niveau:1, titre:'Cinq notes, cinq doigts', duree:'10 min', tempo:60, sig:'4/4',
    objectif:"Poser les cinq doigts de la main droite sur Do, Ré, Mi, Fa, Sol : la position de Do.",
    contenu:`<p>C'est la <b>position de Do</b> : un doigt par touche, du pouce (Do) à l'auriculaire (Sol). On reste dans cette position pour toutes les leçons du niveau 1.</p>${HAUT}${DOIGTS}`,
    conseils:["Si tu te trompes de doigt, recommence lentement : c'est la régularité qui compte, pas la vitesse."],
    d:'C4:1@1 D4@2 E4@3 F4@4 | G4:4@5 | G4:1@5 F4@4 E4@3 D4@2 | C4:4@1' },
  { id:'l04', niveau:1, titre:'Noires, blanches, rondes', duree:'10 min', tempo:60, sig:'4/4',
    objectif:"Tenir une note 1, 2 ou 4 temps.",
    contenu:`<p>Une <b>noire</b> dure 1 temps (note pleine avec une queue). Une <b>blanche</b> dure 2 temps (tête creuse avec une queue). Une <b>ronde</b> dure 4 temps (tête creuse, sans queue).</p>
      <p>Garde la touche enfoncée pendant toute la durée, et compte dans ta tête : 1-2-3-4.</p>${HAUT}`,
    conseils:["Compte à voix haute au début : « 1, 2, 3, 4 »."],
    d:'C4:1@1 C4:1@1 C4:2@1 | D4:1@2 D4:1@2 D4:2@2 | E4:2@3 E4:2@3 | G4:4@5' },
  { id:'l05', niveau:1, titre:'Les silences', duree:'10 min', tempo:60, sig:'4/4',
    objectif:"Lire et respecter un silence : on ne joue rien, mais le temps continue.",
    contenu:`<p>Un <b>soupir</b> (le petit signe en zigzag) vaut une noire : 1 temps de silence. Un <b>demi-soupir</b> écrit sur la ligne du milieu vaut 2 temps.</p>
      <p>En mode « Pas à pas », l'appli attend la prochaine note. Essaie le mode <b>À tempo</b> pour sentir les silences : le métronome continue de battre.</p>${HAUT}`,
    conseils:["Pendant un silence, relâche la touche et garde le pouls en tête."],
    d:'C4:1@1 E4:1@3 r:1 G4:1@5 | G4:1@5 E4:1@3 r:1 C4:1@1 | C4:2@1 r:2 | G4:4@5' },
  { id:'l06', niveau:1, titre:'Au clair de la lune', duree:'10 min', tempo:72, sig:'4/4',
    objectif:"Jouer ta première mélodie, avec les cinq doigts en position de Do.",
    contenu:`<p>Une mélodie que tu connais : tu peux la chanter en même temps. La troisième mesure repart de Do : les deux notes à la fin (Ré, Ré) se jouent avec l'index.</p>${HAUT}${DOIGTS}`,
    conseils:["Chante dans ta tête avant de jouer : la mélodie t'aide à trouver la bonne touche."],
    d:CLAIR_D + ' | ' + CLAIR_D },
  { id:'l07', niveau:1, titre:'La main gauche : les notes graves', duree:'10 min', tempo:60, sig:'4/4',
    objectif:"Jouer Do, Ré, Mi, Fa, Sol avec la main gauche, sous le Do central.",
    contenu:`<p>La main gauche joue dans les <b>graves</b>, écrits en <b>clé de fa</b> (la deuxième portée). Pose l'auriculaire (5) sur le Do grave, le pouce (1) sur le Sol.</p>
      <p>Les doigts de la main gauche sont numérotés comme à droite : 1 = pouce. Mais ils descendent : 5 4 3 2 1 pour monter de Do à Sol.</p>${HAUT}${DOIGTS}`,
    conseils:["Tu peux faire la même chose que la main droite, en miroir : le pouce est au centre."],
    g:'C3:1@5 D3@4 E3@3 F3@2 | G3:4@1 | G3:1@1 F3@2 E3@3 D3@4 | C3:4@5' },
  { id:'l08', niveau:1, titre:'Ode à la joie', duree:'15 min', tempo:84, sig:'4/4',
    objectif:"Jouer un thème célèbre de Beethoven, toujours en position de Do.",
    contenu:`<p>Toute la mélodie tient dans les cinq notes Do–Sol : la main ne bouge pas. Attention à la mesure 4 : <b>noire pointée</b> (1 temps et demi) puis une croche (un demi-temps), puis une blanche.</p>${HAUT}${DOIGTS}`,
    conseils:["Une noire pointée = une noire + la moitié : compte « 1 – 2 – et » puis « 3 – 4 »."],
    d:ODE_D },
  { id:'l09', niveau:1, titre:'Jingle Bells', duree:'15 min', tempo:100, sig:'4/4',
    objectif:"Jouer un refrain connu avec des rythmes variés.",
    contenu:`<p>Une mélodie qui reste dans la position de Do. Les deux dernières notes de la troisième mesure (Do puis Ré) ont un rythme pointé : une note longue, une note courte.</p>${HAUT}`,
    conseils:["Le refrain « Jingle bells » n'est qu'un seul rythme répété : repère-le avant de jouer."],
    d:JINGLE_D },
  { id:'l10', niveau:1, titre:'Une main, puis l\'autre', duree:'10 min', tempo:60, sig:'4/4',
    objectif:"Passer d'une main à l'autre sans perdre le temps.",
    contenu:`<p>Les deux mains jouent à tour de rôle : pendant que l'une joue, l'autre attend. Le silence de l'une est le jeu de l'autre.</p>${HAUT}${DOIGTS}`,
    conseils:["Garde les deux mains au-dessus du clavier, prêtes à jouer."],
    d:'C4:1@1 D4@2 E4@3 F4@4 | r:4 | G4:1@5 F4@4 E4@3 D4@2 | r:4',
    g:'r:4 | C3:1@5 D3@4 E3@3 F3@2 | r:4 | G3:1@1 F3@2 E3@3 D3@4' },

  /* ---------------- niveau 2 ---------------- */
  { id:'l11', niveau:2, titre:'Les deux mains ensemble', duree:'15 min', tempo:60, sig:'4/4',
    objectif:"Jouer une mélodie à droite pendant que la main gauche tient une note.",
    contenu:`<p>La main droite joue la mélodie, la main gauche tient de longues notes en dessous : c'est le principe de l'accompagnement.</p>
      <p>Commence par jouer <b>chaque main seule</b>, puis les deux ensemble, lentement.</p>${HAUT}${DOIGTS}`,
    conseils:["Si une main se trompe, arrête-toi : recommence depuis le début de la mesure."],
    d:'C4:1@1 D4@2 E4@3 F4@4 | G4:4@5 | F4:1@4 E4@3 D4@2 C4@1 | C4:4@1',
    g:'C3:4@5 | E3:4@3 | G3:4@1 | C3:4@5' },
  { id:'l12', niveau:2, titre:'La gamme de Do : la montée', duree:'15 min', tempo:60, sig:'4/4',
    objectif:"Jouer huit notes d'affilée en passant le pouce sous la main.",
    contenu:`<p>Une <b>gamme</b> est une suite de huit notes qui se suivent. Pour aller plus loin que cinq notes, le <b>pouce passe sous</b> le majeur : après Mi (3), le pouce (1) joue Fa.</p>
      <p>Doigté de la main droite qui monte : <b>1 2 3 · 1 2 3 4 5</b>.</p>${HAUT}${DOIGTS}`,
    conseils:["Prépare le passage du pouce dès la note Ré : le pouce glisse sous la main, le poignet reste souple."],
    d:'C4:1@1 D4@2 E4@3 F4@1 | G4@2 A4@3 B4@4 C5@5' },
  { id:'l13', niveau:2, titre:'La gamme de Do : la descente', duree:'15 min', tempo:60, sig:'4/4',
    objectif:"Redescendre la gamme : le majeur passe par-dessus le pouce.",
    contenu:`<p>À la descente, c'est le contraire : le <b>majeur passe par-dessus</b> le pouce. Doigté de la main droite qui descend : <b>5 4 3 2 1 · 3 2 1</b>.</p>${HAUT}`,
    conseils:["Regarde deux notes à l'avance : c'est ce qui rend le passage fluide."],
    d:'C5:1@5 B4@4 A4@3 G4@2 | F4@1 E4@3 D4@2 C4@1' },
  { id:'l14', niveau:2, titre:'La gamme de Do aux deux mains', duree:'20 min', tempo:60, sig:'4/4',
    objectif:"Monter et redescendre la gamme avec les deux mains ensemble, à l'octave.",
    contenu:`<p>La main gauche joue la même gamme une octave plus bas. Son doigté est le miroir du doigté de droite : <b>5 4 3 2 1 · 3 2 1</b> en montant, <b>1 2 3 1 2 3 4 5</b> en descendant.</p>${HAUT}${DOIGTS}`,
    conseils:["Les deux pouces passent sous la main au même moment : un bon exercice de coordination."],
    d:'C4:1@1 D4@2 E4@3 F4@1 | G4@2 A4@3 B4@4 C5@5 | C5@5 B4@4 A4@3 G4@2 | F4@1 E4@3 D4@2 C4@1',
    g:'C3:1@5 D3@4 E3@3 F3@2 | G3@1 A3@3 B3@2 C4@1 | C4@1 B3@2 A3@3 G3@1 | F3@2 E3@3 D3@4 C3@5' },
  { id:'l15', niveau:2, titre:'Frère Jacques', duree:'15 min', tempo:90, sig:'4/4',
    objectif:"Jouer un canon célèbre, et déplacer la main pour atteindre le La.",
    contenu:`<p>Le début reste en position de Do. À la cinquième mesure (Sol, La, Sol, Fa), <b>déplace la main</b> : l'auriculaire va chercher le La, puis la main revient en position de Do. À la fin, le Sol du bas (sous le Do) se joue avec le pouce de la main droite.</p>${HAUT}`,
    conseils:["Chante « Frère Jacques » avant de jouer : les répétitions t'aident à mémoriser."],
    d:FRERE_D },
  { id:'l16', niveau:2, titre:'Trois accords : Do, Fa, Sol', duree:'20 min', tempo:60, sig:'4/4',
    objectif:"Jouer trois notes en même temps, et enchaîner les trois accords les plus utilisés.",
    contenu:`<p>Un <b>accord</b> est fait de trois notes jouées ensemble (une note, une sur deux, une sur deux encore). Les accords de <b>Do</b>, <b>Fa</b> et <b>Sol</b> servent dans des milliers de chansons.</p>
      <p>Pour bouger le moins possible, on utilise des <i>renversements</i> : Do (Do-Mi-Sol), Fa (Do-Fa-La), Sol (Si-Ré-Sol). Le pouce descend d'une note à chaque changement.</p>${HAUT}${DOIGTS}`,
    conseils:["Pose les trois doigts en même temps, sans arpéger : le son est un seul bloc.", "La main gauche joue la note la plus grave de l'accord."],
    d:'C4+E4+G4:4@1+3+5 | C4+F4+A4:4@1+2+5 | B3+D4+G4:4@1+2+5 | C4+E4+G4:4@1+3+5',
    g:'C3:4@5 | F3:4@5 | G3:4@5 | C3:4@5' },
  { id:'l17', niveau:2, titre:'Ode à la joie aux deux mains', duree:'20 min', tempo:72, sig:'4/4',
    objectif:"Ajouter une basse simple sous une mélodie connue.",
    contenu:`<p>Tu connais déjà la mélodie. La main gauche ajoute une basse : des Do, et des Sol au milieu des mesures.</p>${HAUT}`,
    conseils:["Apprends la main gauche seule, deux fois : elle est très simple."],
    d:ODE_D, g:ODE_G },
  { id:'l18', niveau:2, titre:'La valse : trois temps', duree:'20 min', tempo:100, sig:'3/4',
    objectif:"Jouer une mesure à trois temps : une basse, puis deux accords.",
    contenu:`<p>Une <b>valse</b> se compte « 1-2-3, 1-2-3 ». Sur le 1, la main gauche joue la basse ; sur le 2 et le 3, la main droite joue l'accord. C'est le fameux « poum-tchi-tchi ».</p>
      <p>Les trois accords sont Do, Sol, Fa, Do.</p>${HAUT}`,
    conseils:["Insiste un peu sur le 1 : c'est lui qui donne le balancement de la valse."],
    d:'r:1 C4+E4+G4:1@1+3+5 C4+E4+G4:1@1+3+5 | r:1 B3+D4+G4:1@1+2+5 B3+D4+G4:1@1+2+5 | r:1 C4+F4+A4:1@1+2+5 C4+F4+A4:1@1+2+5 | r:1 C4+E4+G4:1@1+3+5 C4+E4+G4:1@1+3+5',
    g:'C3:1@5 r:2 | G2:1@5 r:2 | F2:1@5 r:2 | C3:1@5 r:2' },
  { id:'l19', niveau:2, titre:'Les croches', duree:'15 min', tempo:60, sig:'4/4',
    objectif:"Jouer deux notes dans un temps : les croches.",
    contenu:`<p>Une <b>croche</b> dure un demi-temps : on en joue deux par temps. Elles sont reliées par une barre. On les compte « 1 et 2 et 3 et 4 et ».</p>${HAUT}`,
    conseils:["Joue-les bien régulièrement : deux croches égales, sans presser la seconde."],
    d:'C4:0.5@1 D4@2 E4@3 F4@4 G4@5 F4@4 E4@3 D4@2 | C4:2@1 r:2 | C4:0.5@1 E4@3 D4@2 F4@4 E4@3 G4@5 F4@4 E4@3 | D4:1@2 C4:3@1' },

  /* ---------------- niveau 3 ---------------- */
  { id:'l20', niveau:3, titre:'Joyeux anniversaire', duree:'20 min', tempo:84, sig:'3/4',
    objectif:"Jouer un air très connu, avec un saut d'octave et un début sur le troisième temps.",
    contenu:`<p>Les deux notes de départ tombent sur le <b>3<sup>e</sup> temps</b> (la première mesure commence par deux temps de silence). Pour « Joyeux anniversaire cher·e… », la main saute jusqu'au Sol aigu : <b>prépare ton saut</b> en regardant la note.</p>${HAUT}`,
    conseils:["Chante en jouant : la mélodie te guide sur les sauts."],
    d:ANNIV_D },
  { id:'l21', niveau:3, titre:'Dièses et bémols : les touches noires', duree:'20 min', tempo:60, sig:'4/4',
    objectif:"Jouer les touches noires : un dièse monte d'un demi-ton, un bémol descend d'un demi-ton.",
    contenu:`<p>Un <b>dièse</b> (♯) monte d'un demi-ton : la touche juste à droite. Un <b>bémol</b> (♭) descend d'un demi-ton : la touche juste à gauche. Les touches noires sont des dièses ou des bémols.</p>
      <p>Ici, la gamme chromatique : toutes les notes, blanches et noires, dans l'ordre. Doigté : <b>1 3 1 3 1 2 3 1</b>.</p>${HAUT}`,
    conseils:["Le dièse vaut pour toute la mesure : si tu vois Fa♯, tous les Fa de la mesure sont des Fa♯."],
    d:'C4:1@1 C#4@3 D4@1 D#4@3 | E4@1 F4@2 F#4@3 G4@1 | G#4@3 A4@1 A#4@3 B4@1 | C5:4@2' },
  { id:'l22', niveau:3, titre:'La gamme de Sol majeur', duree:'20 min', tempo:66, sig:'4/4', armure:'G',
    objectif:"Découvrir l'armure : un dièse à la clé, le Fa♯.",
    contenu:`<p>À côté de la clé, le signe <b>♯ sur la ligne du Fa</b> te dit : dans tout le morceau, joue Fa♯ au lieu de Fa. C'est l'<b>armure</b>. Elle indique la <b>tonalité</b> : ici, Sol majeur.</p>
      <p>Même doigté que la gamme de Do : 1 2 3 · 1 2 3 4 5. Pour Fa♯, tu joues une touche noire avec l'annulaire (4).</p>${HAUT}`,
    conseils:["Une gamme de plus : le doigté est le même, seules les touches noires changent."],
    d:'G4:1@1 A4@2 B4@3 C5@1 | D5@2 E5@3 F#5@4 G5@5 | G5@5 F#5@4 E5@3 D5@2 | C5@1 B4@3 A4@2 G4@1',
    g:'G2:1@5 A2@4 B2@3 C3@2 | D3@1 E3@3 F#3@2 G3@1 | G3@1 F#3@2 E3@3 D3@1 | C3@2 B2@3 A2@4 G2@5' },
  { id:'l23', niveau:3, titre:'La gamme de Fa majeur', duree:'20 min', tempo:66, sig:'4/4', armure:'F',
    objectif:"Découvrir un bémol à la clé : le Si♭.",
    contenu:`<p>Cette fois, l'armure a un <b>bémol sur la ligne du Si</b> : on joue Si♭ dans tout le morceau. Le doigté de la main droite change : <b>1 2 3 4 · 1 2 3 4</b>.</p>${HAUT}`,
    conseils:["Pour Si♭ (touche noire), le pouce joue ensuite le Do : tu n'as pas besoin de passer en dessous."],
    d:'F4:1@1 G4@2 A4@3 Bb4@4 | C5@1 D5@2 E5@3 F5@4 | F5@4 E5@3 D5@2 C5@1 | Bb4@4 A4@3 G4@2 F4@1',
    g:'F2:1@5 G2@4 A2@3 Bb2@2 | C3@1 D3@3 E3@2 F3@1 | F3@1 E3@2 D3@3 C3@1 | Bb2@2 A2@3 G2@4 F2@5' },
  { id:'l24', niveau:3, titre:'Douce nuit', duree:'25 min', tempo:66, sig:'3/4',
    objectif:"Jouer une mélodie longue, sur trois temps, avec une basse très simple.",
    contenu:`<p>Un grand classique de Noël, en trois temps. La noire pointée suivie de la croche donne le balancement. Joue <b>lentement</b> et chante dans ta tête.</p>${HAUT}`,
    conseils:["Travaille par phrases de quatre mesures.", "La main gauche ne joue qu'une note par mesure."],
    d:DOUCE_D, g:DOUCE_G },
  { id:'l25', niveau:3, titre:'Accords mineurs : La, Ré, Mi', duree:'20 min', tempo:60, sig:'4/4',
    objectif:"Reconnaître et jouer des accords mineurs, plus tristes que les majeurs.",
    contenu:`<p>Un accord <b>mineur</b> a une tierce plus petite : il sonne plus sombre. <b>La mineur</b> (La-Do-Mi), <b>Ré mineur</b> (Ré-Fa-La), <b>Mi mineur</b> (Mi-Sol-Si).</p>${HAUT}`,
    conseils:["Compare avec l'accord majeur : c'est un demi-ton d'écart sur la note du milieu."],
    d:'C4+E4+A4:4@1+2+5 | D4+F4+A4:4@1+3+5 | E4+G4+B4:4@1+3+5 | C4+E4+A4:4@1+2+5',
    g:'A2:4@5 | D3:4@5 | E3:4@5 | A2:4@5' },
  { id:'l26', niveau:3, titre:'La suite d\'accords de la pop', duree:'25 min', tempo:72, sig:'4/4',
    objectif:"Jouer Do – Sol – La mineur – Fa : la suite d'accords de centaines de chansons.",
    contenu:`<p>Ces quatre accords, dans cet ordre, accompagnent énormément de chansons. Retiens-les : tu pourras accompagner beaucoup de morceaux avec seulement ça.</p>${HAUT}`,
    conseils:["Change d'accord en bougeant le moins possible : les doigts se déplacent peu."],
    d:'C4+E4+G4:4 | B3+D4+G4:4 | C4+E4+A4:4 | C4+F4+A4:4 | C4+E4+G4:4 | B3+D4+G4:4 | C4+E4+A4:4 | C4+F4+A4:4',
    g:'C3:4 | G2:4 | A2:4 | F2:4 | C3:4 | G2:4 | A2:4 | F2:4' },

  /* ---------------- niveau 4 ---------------- */
  { id:'l27', niveau:4, titre:"La basse d'Alberti", duree:'25 min', tempo:60, sig:'4/4',
    objectif:"Jouer un accompagnement en notes brisées à la main gauche.",
    contenu:`<p>La main gauche joue les notes de l'accord l'une après l'autre : <b>bas – haut – milieu – haut</b>. C'est la <b>basse d'Alberti</b>, très utilisée dans la musique classique.</p>
      <p>Apprends d'abord la main gauche seule, puis ajoute la mélodie.</p>${HAUT}`,
    conseils:["Joue la main gauche doucement : c'est la mélodie qui doit chanter."],
    d:'E4:2@3 D4:2@2 | C4:4@1 | D4:2@2 B3:2@1 | C4:4@1',
    g:'C3:0.5@5 G3@1 E3@3 G3@1 C3@5 G3@1 E3@3 G3@1 | C3@5 G3@1 E3@3 G3@1 C3@5 G3@1 E3@3 G3@1 | B2@5 G3@1 D3@3 G3@1 B2@5 G3@1 D3@3 G3@1 | C3@5 G3@1 E3@3 G3@1 C3@5 G3@1 E3@3 G3@1' },
  { id:'l28', niveau:4, titre:'Des arpèges aux deux mains', duree:'25 min', tempo:60, sig:'4/4',
    objectif:"Jouer les notes d'un accord l'une après l'autre (un arpège) à la main droite.",
    contenu:`<p>Un <b>arpège</b> joue les notes de l'accord une par une, en montant puis en redescendant. La main gauche donne la basse. On retrouve la suite Do – Fa – Sol – Do.</p>${HAUT}`,
    conseils:["Garde la main souple : le poignet accompagne le mouvement."],
    d:'C4:0.5@1 E4@2 G4@3 C5@5 G4@3 E4@2 C4@1 E4@2 | C4@1 F4@2 A4@3 C5@5 A4@3 F4@2 C4@1 F4@2 | B3@1 D4@2 G4@3 B4@5 G4@3 D4@2 B3@1 D4@2 | C4+E4+G4:4@1+3+5',
    g:'C3:4@5 | F3:4@5 | G3:4@5 | C3:4@5' },
  { id:'l29', niveau:4, titre:'Le canon de Pachelbel', duree:'30 min', tempo:60, sig:'4/4', armure:'D',
    objectif:"Jouer la suite d'accords la plus célèbre, avec sa basse qui descend.",
    contenu:`<p>Huit accords, deux temps chacun, en <b>ré majeur</b> (deux dièses : Fa♯ et Do♯). La basse dessine une ligne qui descend, que l'on retrouve dans beaucoup de chansons.</p>${HAUT}`,
    conseils:["Joue la basse seule d'abord : c'est elle qui conduit."],
    d:CANON_D + ' | ' + CANON_D, g:CANON_G + ' | ' + CANON_G },
  { id:'l30', niveau:4, titre:'Rythmes pointés', duree:'20 min', tempo:72, sig:'4/4',
    objectif:"Jouer une note longue suivie d'une note courte : le rythme pointé.",
    contenu:`<p>Une <b>noire pointée</b> (1 temps et demi) est suivie d'une croche (un demi-temps). Compte : « 1 – (2) – et · 3 – (4) – et ».</p>${HAUT}`,
    conseils:["Bats la pulsation du pied : la croche tombe juste avant le temps suivant."],
    d:'C4:1.5@1 D4:0.5@2 E4:1.5@3 F4:0.5@4 | G4:1.5@5 F4:0.5@4 E4:1.5@3 D4:0.5@2 | C4:1.5@1 E4:0.5@3 G4:1.5@5 E4:0.5@3 | C4:4@1' },
  { id:'l31', niveau:4, titre:'Ballade : la suite pop aux deux mains', duree:'30 min', tempo:70, sig:'4/4',
    objectif:"Accompagner avec des arpèges à la main gauche et des accords à la main droite.",
    contenu:`<p>La main gauche arpège (racine – quinte – tierce – quinte) sur chaque accord, pendant que la main droite tient les accords : Do, Sol, La mineur, Fa.</p>${HAUT}`,
    conseils:["Commence lentement, mains séparées, puis assemble."],
    d:'C4+E4+G4:2 C4+E4+G4:2 | B3+D4+G4:2 B3+D4+G4:2 | C4+E4+A4:2 C4+E4+A4:2 | C4+F4+A4:2 C4+F4+A4:2',
    g:'C3:0.5 G3 E3 G3 C3 G3 E3 G3 | G2 D3 B2 D3 G2 D3 B2 D3 | A2 E3 C3 E3 A2 E3 C3 E3 | F2 C3 A2 C3 F2 C3 A2 C3' },

  /* ---------------- niveau 5 ---------------- */
  { id:'l32', niveau:5, titre:'Hanon n°1 (début)', duree:'30 min', tempo:60, sig:'4/4',
    objectif:"Muscler les doigts avec le célèbre exercice de Hanon : huit doubles-croches par groupe.",
    contenu:`<p>Dans l'exercice n°1 de Hanon, les deux mains jouent le même motif, à l'octave, en montant par degrés. Le doigté est toujours <b>1-2-3-4-5-4-3-2</b> à droite et <b>5-4-3-2-1-2-3-4</b> à gauche.</p>
      <p>Commence très lentement (à 60, chaque note dure un quart de temps).</p>${HAUT}`,
    conseils:["Joue fort et détaché au début, puis de plus en plus régulier.", "Stop dès que les doigts se crispent."],
    d:HANON_D, g:HANON_G },
  { id:'l33', niveau:5, titre:'Syncopes', duree:'30 min', tempo:72, sig:'4/4',
    objectif:"Jouer des notes entre les temps : les syncopes.",
    contenu:`<p>Une <b>syncope</b> est une note qui démarre entre deux temps et se prolonge sur le temps suivant. On la sent comme un léger décalage. Compte « 1 et 2 et 3 et 4 et » et place les notes sur les « et ».</p>${HAUT}`,
    conseils:["Tape le rythme sur la table avant de jouer les notes."],
    d:'C5:0.5@5 G4:1@2 C5:1@5 G4:1@2 E4:0.5@3 | D5:0.5@5 A4:1@3 D5:1@5 A4:1@3 F4:0.5@2 | E5:0.5@5 B4:1@3 E5:1@5 B4:1@3 G4:0.5@2 | C5:4@5',
    g:'C3:4 | D3:4 | E3:4 | C3:4' }
];
